apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenseapp
  labels:
    app: expenseapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expenseapp
  template:
    metadata:
      labels:
        app: expenseapp
    spec:
      containers:
      - name: expenseapp
        image: 920373010296.dkr.ecr.eu-west-1.amazonaws.com/ecr-repo 
        ports:
        - containerPort: 8000
