apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense
  template:
    metadata:
      labels:
        app: expense
    spec:
      containers:
      - name: expense
        image: sledgy/expense:latest
        ports:
        - containerPort: 8000 # Replace with the port your app listens on
