apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense
  template:
    metadata:
      labels:
        app: expense
    spec:
      containers:
      - name: expense-container
        image: gcr.io/gold-circlet-439215-k9/gcr-repo/expense:latest  # Replace <your-gcp-project-id> with your GCP project ID
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: expense
spec:
  type: LoadBalancer
  selector:
    app: expense
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
