apiVersion: v1
kind: Service
metadata:
  name: expense-service
spec:
  selector:
    app: expense
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # To expose the service externally, change to ClusterIP for internal access
