apiVersion: v1
kind: Service
metadata:
  name: expense-service  # Name updated to match app name
spec:
  type: LoadBalancer  # Exposes the app via a public IP
  ports:
  - port: 80
    targetPort: 8000  # Ensure this matches your app’s exposed port
  selector:
    app: expense
